version: '3.8'
services:

  spark-streaming:
    build: ./spark_streaming
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: ["python", "streaming_job.py"]
    networks:
      - shared_net

  spark-batch:
    build: ./spark_batch
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./spark_batch:/opt/spark_batch
    command: ["python", "batch_job.py"]
    networks:
      - shared_net
    ports:
      - "4040:4040"
  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - shared_net

  spark-worker1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # UI cho Spark Worker
    networks:
      - shared_net

  spark-worker2:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8082"   # UI cho Spark Worker
    networks:
      - shared_net

  spark-worker3:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8083:8083"   # UI cho Spark Worker
    networks:
      - shared_net    
networks:
  shared_net:
    external: true
