version: '3.8'
services:
  fake-producer:
    build: ./producer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
    volumes:
      - /home/huaquan/desktop/datn-1/archive:/archive
    command: ["python", "producer.py"]
    networks:
      - shared_net

  spark-streaming:
    build: ./spark_streaming
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: ["python", "streaming_job.py"]
    networks:
      - shared_net

  spark-batch:
    build: ./spark_batch
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9093
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /home/huaquan/desktop/datn-1/archive:/archive
    command: ["python", "batch_job.py"]
    networks:
      - shared_net
    ports:
      - "4040:4040"
networks:
  shared_net:
    external: true
