version: '3.8'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    ports:
      - "50070:50070"   # cổng web UI NameNode
      - "9000:9000"   # cổng NameNode RPC
    environment:
      - CLUSTER_NAME=demo-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=3
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - shared_net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode1
    ports:
      - "9864:9864"   # cổng web UI DataNode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=3
    volumes:
      - datanode1:/hadoop/dfs/data
    networks:
      - shared_net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=3
    volumes:
      - datanode2:/hadoop/dfs/data
    networks:
      - shared_net

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode3
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=3
    volumes:
      - datanode3:/hadoop/dfs/data
    networks:
      - shared_net

volumes:
  namenode:
  datanode1:
  datanode2:
  datanode3:

networks:
  shared_net:
    external: true


