version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"
      - "9301:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5600:5601"
    depends_on:
      - elasticsearch

  serving-api:
    build: ./serving_api
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

networks:
  shared_net:
    external: true
